server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-api
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users, /api/users/**
          filters:
            - RewritePath=/api/users(?<segment>.*), /users$\{segment}

        - id: user-service-direct
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users, /users/**

        - id: event-service-api
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/events, /api/events/**
          filters:
            - RewritePath=/api/events(?<segment>.*), /events$\{segment}

        - id: order-service-api
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders, /api/orders/**
          filters:
            - RewritePath=/api/orders(?<segment>.*), /orders$\{segment}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
