server:
  port: 8087

spring:
  application:
    name: SEARCH-SERVICE
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: search-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

opensearch:
  url: http://localhost:9200
  index: events
