server:
  port: 8090

spring:
  application:
    name: SEARCH-SERVICE
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: search-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

opensearch:
  url: ${OPENSEARCH_URL:http://localhost:9200}
  index: events
